### ISSUE TITLE
Contact Information module's Email address is not shown

### ISSUE THREAD

**Issue by ash-f** [PrestaShop/hummingbird#560] opened 2023-10-26 17:01 UTC
Contact Information module does not show the email address with Hummingbird theme.
Email option is enabled in the module setting.

Prestashop 8.12
Hummingbird 0.1.6

**Comment by florine2623** [comment] 2024-03-29 10:09
Can't reproduce your issue :

<img width="1191" alt="Screenshot 2024-03-29 at 11 08 23" src="https://github.com/PrestaShop/hummingbird/assets/16019289/ea259cb3-2d9b-4eac-8dc5-0c87637e447c">

So I'm closing it.

**Closed by florine2623** 2024-03-29 10:09 UTC
