### ISSUE TITLE
what about the classic theme modules?

### ISSUE THREAD

**Issue by alfonsolr09** [PrestaShop/hummingbird#133] opened 2021-12-09 23:48 UTC
the modules that were created to work with the classic theme what will happen to them? Will they be updated or will those modules not work? 
example: https://addons.prestashop.com/es/menu/41931-cart-dropdown.html

**Comment by SharakPL** [comment] 2021-12-10 00:25
Yeah, I'm not sure current approach is suited for prestashop. For example [new blockwishlist module](https://github.com/PrestaShop/blockwishlist) uses Vue on the front so it's already quite heavy. Archive of this module alone weights more than archive of whole classic theme. Over twice more unpacked. And you can't even override styles like before because they are inlined in Vue component so you have to duplicate a lot and each property would have to be marked `!important` to use different colors than forced by the module.

If Vue is going to be used like this on the front, then each module should have complete style customization in admin panel. But honestly I'm not sure this is good approach. I think all styles should be still made in .scss files only. Otherwise developing new themes will be harder.

**Comment by NeOMakinG** [comment] 2021-12-14 13:35
- Vue won't be used in the new theme
- non-heavy modules should work, or they will need to update according to the fact that the new theme use bootstrap 5 now
- The JS API should stay the same (events and events API), but it will be refacto in order to split some logics and probably avoid the core part

This is everything I can say for now

**Comment by alfonsolr09** [comment] 2021-12-17 01:48
Is an update of the modules being carried out at the same time as this theme is developed?

**Comment by NeOMakinG** [comment] 2021-12-17 09:07
> Is an update of the modules being carried out at the same time as this theme is developed? 🤔 I mean that this theme should be functional with the modules from the day the final version is released and not having to wait for one or more module updates

As I'm the only one working on the theme with some contributors, we don't have any final date in order to release the theme, there are a LOT of things to do before 😄 

If modules need an update in order to be compatible, it will be done later don't worry, because we plan to add a key inside the theme configuration so modules would be able to provide a different markup if the theme use bootstrap 5 for example...

Be patient 🙏

**Comment by NeOMakinG** [comment] 2021-12-17 09:08
@alfonsolr09 the first step would be to be compatible with native modules, we've no hand on the compatibility with community modules and regarding the changes inside the theme, a lot will break with it until their developers release an update with a way to see if the current website is using a specific theme!

**Comment by alfonsolr09** [comment] 2021-12-17 15:27
I mean native modules.
I know that third-party modules some will be updated and many others will not, but that does not matter to me ...

**Comment by matks** [comment] 2022-04-10 12:49
> If modules need an update in order to be compatible, it will be done later don't worry, because we plan to add a key inside the theme configuration so modules would be able to provide a different markup if the theme use bootstrap 5 for example...

If I understand: when hummingbird theme is complete enough, each native module will receive some improvements that allow them to work with both Classic theme and Hummingbird theme.

**Comment by NeOMakinG** [comment] 2022-08-04 14:31
Duplicate of https://github.com/PrestaShop/hummingbird/issues/255

Not sure that every module will be compatible anyway as we updated bootstrap, we can't be compatible with the whole addons catalog for sure, but at least we can be compatible with native modules first

Every developer will need to override their modules TPLs in order to make them compatible!

What we should think about is providing a way to detect the current bootstrap version on the current theme!

**Closed by NeOMakinG** 2022-08-04 14:31 UTC
